export { HeroPage } from './hero/HeroPage'
export { NavBar } from './navBar/NavBar'
export { HomeContent } from './homeContent/HomeContent'
export { SearchResultsPage } from './searchResults/SearchResultsPage'
export { UploadImagePage } from './uploadImage/UploadImagePage'
