export { HeroPage } from './hero/HeroPage'
export { PrimaryNav } from './navBar/PrimaryNav'
export { SecondaryNav } from './navBar/SecondaryNav'
export { HomeContent } from './homeContent/HomeContent'
export { SearchResultsPage } from './searchResults/SearchResultsPage'
export { UploadImagePage } from './uploadImage/UploadImagePage'
